---
title: "Modèle 3"
author: "Marc-André Désautels"
date: "7 mai 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE)
library(tidyverse)
library(lubridate)
library(googlesheets)
library(stringr)
library(rtweet)
library(plotly)
library(scales)

# Définition des fonctions pour le calcul des mesures sur les numéros de série.

N1 <- function(ech){
  return(round(2*median(ech)-1))
}

N2 <- function(ech){
  return(round(2*mean(ech)-1))
}

N3 <- function(ech){
  return(round(max(ech)+min(ech)-1))
}

N4 <- function(ech){
  l <- length(unique(ech))
  return(round((l+1)/l*max(ech)-1))
}

N5 <- function(ech){
  l <- length(unique(ech))
  return(round((max(ech)-min(ech))*(l+1)/(l-1)))
}
```

<!-- Googlesheets -->

```{r echo = FALSE}
tesla <- gs_key("188iQarE-7M49xKcTaCxEkQVd1A1FH5bFgJ5d9sQfJck")
```

```{r peupler, eval = FALSE, echo = FALSE}
url <- "https://docs.google.com/spreadsheets/d/1YeLtMxFt9Lh8mndZhjOqrzFfWQ_r5T9LS-l3gQzPXCk/edit"

for (i in seq(1, 6000, 1000)){
  contenu <- paste0("=IMPORTRANGE(\"",url,"\",\"All Entries!A",i,":AI",i+999,"\")")
  cellule <- paste0("A",i)
  gs_edit_cells(tesla , ws = "All Entries", anchor = cellule, input = contenu)
}

contenu <- paste0("=IMPORTRANGE(\"",url,"\",\"Production!B49:Q131\")")
gs_edit_cells(tesla, ws = "Production", anchor = "A1", input = contenu)
```

```{r read-google,echo = FALSE}
data <- tesla %>%
  gs_read(ws = "All Entries")
alldata <- data[3:nrow(data),]
colnames(alldata) <- data[2,]
proddata <- tesla %>%
  gs_read(ws = "Production")
```

```{r clean-google, echo = FALSE}
date <- c("Reservation date",
          "Invite date or access date to the Configurator",
          "Configuration date",
          "VIN assignment date",
          "Scheduled delivery date",
          "Last update",
          "Calculated delivery date")
time <- c("Reservation time")
int <- c("VIN (clean version x=5)")
cleanalldata <- alldata %>%
  mutate_at(date, funs(dmy)) %>%
  mutate_at(time, funs(hm)) %>%
  mutate_at(int, funs(as.integer))
cleanproddata <- proddata %>%
  mutate_at("Date", funs(dmy)) %>%
  mutate_at("Total units", funs(as.integer))
```

```{r data-google, echo = FALSE}
INVITES <- cleanalldata %>%
  filter(!is.na(`VIN (clean version x=5)`) & !is.na(`VIN assignment date`)) %>%
  rename(vin_invites = `VIN (clean version x=5)`, date = `VIN assignment date`) %>%
  arrange(date)
n4 <- vector(mode = "double", length = nrow(INVITES))
n5 <- vector(mode = "double", length = nrow(INVITES))
for (i in seq(length(n4))){
  n4[i] <- N4(INVITES$vin_invites[1:i])
  n5[i] <- N5(INVITES$vin_invites[1:i])
}
INVITES <- as.tibble(cbind(INVITES, tibble(N4 = n4, N5 = n5)))

PRODUCTION <- cleanproddata %>%
  filter(!is.na(`Date`) & !is.na(`Total units`)) %>%
  rename(date = `Date`, total_unites = `Total units`) %>%
  arrange(date)
```

<!-- Rtweet -->

```{r read-tweet, echo = FALSE}
Model3VINs <- get_timeline("Model3VINs", n = 3200)
Model3VINs$text <- str_to_lower(Model3VINs$text)
```

```{r data-tweet, echo = FALSE}
NHSTA <- Model3VINs %>%
  filter(str_detect(text, "highest vin is (\\d+)") == TRUE) %>%
  mutate(vin_nhsta = as.integer(str_match(text, "highest vin is (\\d+)")[,2])) %>%
  mutate(date = as_date(created_at)) %>%
  select(date, vin_nhsta) %>%
  arrange(date)
```

## Graphiques

```{r plot, echo=FALSE , fig.height=8, fig.width=8}
g <- ggplot()+
  geom_point(data = INVITES, mapping = aes(x = date, y = vin_invites), alpha = 0.5, size = 0.75)+
  #geom_line(data = INVITES, mapping = aes(x = date, y = N4), color = "green")+
  #geom_line(data = INVITES, mapping = aes(x = date, y = N5), color = "yellow")+
  geom_point(data = PRODUCTION, mapping = aes(x = date, y = total_unites), color = "red")+
  geom_line(data = PRODUCTION, mapping = aes(x = date, y = total_unites), color = "red")+
  geom_step(data = NHSTA, mapping = aes(x = date, y = vin_nhsta), color = "blue", size = 1)+
  labs(
    x = "Date d'assignation du numéro VIN",
    y = "Numéro VIN"
  )+
  scale_x_date(breaks = date_breaks("1 month"), limits = c(as.Date("2017-11-01"),NA))
ggplotly(g)
```

## Statistiques


